language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.3"
    - "3.4"
env:
    matrix:
        # Vdirsyncer
        - PACKAGE=coverage VERSION=3.7.1
        - PACKAGE=lxml VERSION=3.4.1
        - PACKAGE=pyyaml VERSION=3.11
        # Werkzeug
        - PACKAGE=greenlet VERSION=0.4.5
        - PACKAGE=pyopenssl VERSION=0.14
        -   PACKAGE=six VERSION=1.8.0
        - PACKAGE=cryptography VERSION=0.6.1
        -   PACKAGE=cffi VERSION=0.8.6
        -     PACKAGE=pycparser VERSION=2.10
    global:
        secure: fwk013cuhbsbGjadDJfWNf7/mMAUb5Pgqw1J5QB0Ob37jKPCxJJN2SsWeRqaC+mrXsiBZ43DqMQ+n+U20cxPK15XRUip/fXHsGDpzUwl79nIUovgrtWWtVaj6RTtuk8httDWpaM3SE+Jy2UAzkOljzuGK6h7KwGQ8hSTvQjYPak=

install: true
script: sh build.sh
